squashfs: reduce the memory consumed by unsquashfs to uncompress a single file (#16391)
* squashfs: reduce the memory consumed by unsquashfs to uncompress a single file

On low-end platforms such as RPi Zero 2W, unsquashfs can fail trying to
unsquash a single file with the following error:

stateengine.go:161: state ensure error: devicemgr: cannot seed: cannot run unsquashfs:
- - - - -
Total memory requested is more than 75% of physical memory.
Unsquashfs uses memory to cache data from disk to optimise performance.
It is pointless to ask it to use more than this amount of memory, as this
causes thrashing and it is thus self-defeating.
FATAL ERROR: Requested memory size too large

This commit limits both the data and fragment queue sizes used by
unsquashfs in order to limit the memory consumption to a minimum.

Signed-off-by: Nicolas Harnois <nicolas.harnois@canonical.com>

* squashfs: use long names for unsquashfs options

Signed-off-by: Nicolas Harnois <nicolas.harnois@canonical.com>

* squashfs: reduce the memory consumed by unsquashfs

On low-end platforms such as RPi Zero 2W, unsquashfs can further fail trying to
unsquash snaps during install time:

stateengine.go:161: state ensure error: devicemgr: cannot seed: exit status 1;
 contact developer

This commit limits both the data and fragment queue sizes used by
unsquashfs for every call to unsquashfs in order to limit the memory
consumption to a minimum.

A simple benchmark have been conducted on an Intel-based laptop, and no
performance degradation was noticed:

$ time unsquashfs -quiet -no-xattrs -no-progress -force -dest tmp firefox_7720.snap

real	0m0.325s
user	0m1.376s
sys	0m0.523s

$ time unsquashfs -quiet -fr 16 -da 16 -no-xattrs -no-progress -force -dest tmp firefox_7720.snap

real	0m0.297s
user	0m1.328s
sys	0m0.459s

Signed-off-by: Nicolas Harnois <nicolas.harnois@canonical.com>

---------

Signed-off-by: Nicolas Harnois <nicolas.harnois@canonical.com>